# Global
site_analytics: 
hoster: <a href="https://github.io" target="_blank">Github Pages</a>
site_logo: /images/favicon.png
snow: true

# Top Menu
menu:
  index: /
  archives: /archives/
  friends: /friends/
  about: /about/
label:
  index: <i class="fa fa-home"></i>&nbsp;首页
  archives: <i class="fa fa-file"></i>&nbsp;档案馆
  friends: <i class="fa fa-mars-double"></i>&nbsp;后宫团
  about: <i class="fa fa-rocket"></i>&nbsp;关于咱

# Footer
qqg_link: 
contact:
  weibo: 
  tweibo: 
  mail: 
  twitter: 
  facebook: 
  linkedin: 
  github: https://github.com/Candinya
  
# Post Page
posts:
  show_cc: true
  donate: false
  share: true
  comments: true

# Disqus
disqus:
  shortname: candiblog

# Widgets
sidebar: right
widgets:
- about
- category
- tagcloud
- posts
avatarUri: https://cn.gravatar.com/avatar/a7f9e15fef26e0a540edc977e21cb3eb

# Code Highlight Themes: normal | night | night eighties | night blue | night bright
highlight_theme: night eighties