# 调试模式开关，在生成静态文件前记得关闭哦~
debug_mode: true

# 站点信息
title: 
subtitle: 
author: 

# 全站相关，请不要忘了<script>
site_player: #这里放全站播放器代码（如果有的话
site_analytics: #这里放统计代码（如果有的话

# 下雪，具体参数请修改snow.kr.js
snow: true

# 顶部菜单栏
menu:
  index: /
  archives: /archives
  friends: /friends
  about: /about
label:
  index: <i class="fa fa-home"></i>&nbsp;首页
  archives: <i class="fa fa-file"></i>&nbsp;档案馆
  friends: <i class="fa fa-mars-double"></i>&nbsp;后宫团
  about: <i class="fa fa-rocket"></i>&nbsp;关于咱

# 底部
show_qqg: true
contact:
  weibo: 
  tweibo: 
  mail: 
  twitter: 
  facebook: 
  linkedin: 
  github: 
  
# 文章
posts:
  show_cc: true
  donate: true
  share: true

# 内容，不知道fancybox是个啥就删掉了
excerpt_link: 阅读全文

# 侧边栏小组件，bio是about里显示的文字
sidebar: right
widgets:
- about
- category
- tagcloud
- posts
- archive

bio: 欸？我是谁？我在哪儿？

# API，还没完全搭建完成
api:
  pre: https://api.lcy.moe?api=
  qr: qr&cont=
  qq: qq&usr=


