################## 系统配置 ##################
# 依赖文件
vendors:
  npm_cdn: "" # 默认使用站点直接提供
  packages:
    nprogress:
      version: "0.2.0"
    qr-code-styling:
      version: "1.6.0-rc.1"
    font-awesome:
      version: "4.7.0"
    viewerjs:
      version: "1.11.6"

# 启用更新检查
check_update: true

# 规范重复内容 URL ( https://developer.mozilla.org/zh-CN/docs/Web/HTML/Attributes/rel#canonical )
canonical: true

# 启用页面局部更新功能
pjax: true

# 启用文章内图片点击放大功能
viewerjs: true

# 搜索
search:
  provider: "local" # local / external / none
  path:
    page: search
    index_file: search-index.json
  includes: []
  # - post
  # - page
  content: true # 包含文章和页面的内容

################## 样式配置 ##################

# 图片配置
image:
  favicon: "" # 站点图标
  avatar: "/images/user.svg" # 个人信息挂件上的头像
  banner: # 站点横幅
    light: "" # 亮色模式
    dark: "" # 暗色模式
  background: # 站点背景
    light: "" # 亮色模式
    dark: "" # 暗色模式
  about: # 介绍卡片
    light: "/images/default.png" # 亮色模式
    dark: "/images/default.png" # 暗色模式

# 顶部导航栏配置
nav:
  auto_hide: true
  items: []
  # - label: 这个菜单的标签文字
  #   icon: 这个菜单前的图标（在 tabler icons 图标库中选择，可以不设置）
  #   url: 这个菜单指向的链接（站内或是站外均可）
  #   submenu: 这个菜单是否为一个二级菜单，有了这个选项就会忽略上面的 url
  #     - label: 二级菜单项的标签文字
  #       icon: 二级菜单前的图标（在 tabler icons 图标库中选择，可以不设置）
  #       url: 二级菜单项指向的链接

# 文章的列表配置（首页/分页/标签页）
index:
  style: "card" # card / half

# Footer 页脚配置
footer:
  links: []
  # - icon: # 和 html 二选一，该选项表示使用来自 tabler icons 图标库，内容为图标库中的唯一标识
  #   html: # 和 icon 二选一，该选项表示插入自定义的 HTML 作为标识，例如您可在此放置一串 svg
  #   link: # 按钮导向的目标链接
  #   addition: target="_blank" rel="nofollow"
  components: # 一些有特色的组件 （其他的请在 additional 自行追加）
    uptime:
      since: "2018/05/06 17:03:12"
      text: "本站已运行"
    author:
      homepage: ""
    additional: [] # 托管信息等

# Post 文章配置
posts:
  default_cover: "/images/default.png" # 没有头图的文章使用的默认图片
  donate: true
  share: true
  word_count:
    enable: true
    threshold: 1500
    estimate_wavy: true # 在文章字数处显示表示大约字数的波浪号
  expire_after: 30 # 天

# Page 一般页面配置
pages:
  donate: true
  share: true

# 代码高亮
syntax_highlighter:
  theme: night-eighties # 代码高亮主题（请参照具体的高亮插件对应的主题样式）

# 侧边栏小挂件
sidebar:
  location: right
  widgets: []
  # - about
  # - splitter
  # - toc
  # - category
  # - tagcloud
  # - posts
  mobile_toc:
    hide: false
    hide_id: false

# 分享组件设置
share:
  enable: true
  title: "分享"
  message: "分享提示信息"
  platforms: []
  # - name: ""
  #   icon: ""
  #   html: ""
  #   color: ""
  #   link: ""

# 打赏组件设置
donate:
  enable: true
  title: "打赏"
  message: "打赏提示信息"
  qrcode_placeholder: ""
  platforms: []
  # - name: ""
  #   icon: ""
  #   html: ""
  #   color: ""
  #   link: ""
  #   qrcode: ""

# 站点离开提示
inactive_notice:
  enable: true
  favicon:
    leave: "/images/failure.png"
  message:
    leave: "{{{(>_<)}}}哦哟，崩溃啦~"
    return: "(*´∇｀*)欸，又好啦~"

# 版权说明
copyright_notice:
  in_page:
    enable_at: []
    # - post
    # - page
    template: 本作品采用 <a rel="license nofollow" target="_blank" href="https://creativecommons.org/licenses/by-sa/4.0/">知识共享署名-相同方式共享 4.0 国际许可协议</a> 进行许可
  append_copy:
    enable: true
    threshold: 150
    template: |
      $NEWLINE
      -------------------------
      该内容采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
      作者：$AUTHOR
      来源：$TITLE
      链接：$LINK

# 评论系统
comments:
  core:
    enable_at: []
    # - index
    # - post
    # - page
    template:
      _shared: ""
      index: ""
      post: ""
      page: ""
  count:
    enable_at: []
    # - index
    # - post
    template:
      _shared: ""
      index: ""
      post: ""

# 访问数量统计
visit_count:
  enable_at: []
  # - index
  # - post
  template:
    _shared: ""
    index: ""
    post: ""

################## 额外的注入代码 ##################
additional_injections:
  head: "" # 搜索引擎的站点验证
  footer: "" # 额外的组件
  after_footer: "" # 站点分析脚本
