################## 系统配置 ##################
# 依赖文件
vendors:
  packages:
    bootstrap: 
      version: "5.3.3"
    nprogress: 
      version: "0.2.0"
    qrcode_js: 
      version: "1.0.0"
    "@tabler/icons-webfont": 
      version: "3.4.0"
    viewerjs:
      version: "1.11.6"

# 检查更新
check_update: true

# 规范重复内容 URL ( https://developer.mozilla.org/zh-CN/docs/Web/HTML/Attributes/rel#canonical )
canonical: true

# 搜索
search:
  enable: true
  path: search.json
  field: post # page | post | all. Default post
  content: true # Include post | page content

################## 样式配置 ##################

# 图片配置
image:
  favicon: "" # 站点图标
  avatar: "/images/user.svg" # 个人信息挂件上的头像
  banner:     # 站点横幅
    light: "" # 亮色模式
    dark: ""  # 暗色模式
  background: # 站点背景
    light: "" # 亮色模式
    dark: ""  # 暗色模式
  about:      # 介绍卡片
    light: "/images/about.webp" # 亮色模式
    dark: "/images/about.webp"  # 暗色模式

# 顶部导航栏配置
top_nav:
  auto_hide: true
  items: []
  # - label: 这个菜单的标签文字
  #   icon: 这个菜单前的图标（在 tabler icons 图标库中选择，可以不设置）
  #   url: 这个菜单指向的链接（站内或是站外均可）
  #   submenu: 这个菜单是否为一个二级菜单，有了这个选项就会忽略上面的 url
  #     - label: 二级菜单项的标签文字 
  #       icon: 二级菜单前的图标（在 tabler icons 图标库中选择，可以不设置）
  #       url: 二级菜单项指向的链接

# 文章的列表配置（首页/分页/标签页）
post_index:
  post_type: false
  read_count: true
  comment_count: true

# Footer 页脚配置
footer_links: []
# - icon: # 和 html 二选一，该选项表示使用来自 tabler icons 图标库，内容为图标库中的唯一标识
#   html: # 和 icon 二选一，该选项表示插入自定义的 HTML 作为标识，例如您可在此放置一串 svg
#   link: # 按钮导向的目标链接
#   currentPage: # 可选，默认为否，启用该选项表示在当前页内打开目标链接

# 一些有特色的组件 （其他的请在 additional_injections 自行追加）
footer_components:
  uptime:
    since: "2018/05/06 17:03:12"
    text: 本站已运行

# Post 文章页配置
posts:
  default_cover: "/images/about.webp" # 没有头图的文章使用的默认图片
  show_cc: true
  donate: true
  share: true
  word_count: 
    enable: true
    threshold: 1500
    estimate_wavy: true # 在文章字数处显示表示大约字数的波浪号
  expire_after: 30 # 天

pages:
  show_cc: true
  donate: true
  share: true

# 代码高亮
code_highlight:
  theme: night-eighties # 代码高亮主题（light | night | night-eighties | night-blue | night-bright）

# 侧边栏小挂件
sidebar:
  location: right
  widgets: []
  # - about
  # - splitter
  # - toc
  # - category
  # - tagcloud
  # - posts
  mobile_toc: 
    hide: false
    hide_id: false

# 分享组件设置
share:
  platforms: []
  # - icon: ""
  #   color: ""
  #   qrcode: true
  #   link_template: ""

# 捐赠组件设置
donate:
  title: "支持我~"
  subtitle: "扫一扫，好不好？"
  platforms: []
  # - icon: ""
  #   text: ""
  #   qrcode: ""

# 站点离开提示
inactive_notice:
  enabled: true
  favicon:
    leave: "/images/failure.ico"
  message:
    leave: "{{{(>_<)}}}哦哟，崩溃啦~"
    return: "(*´∇｀*)欸，又好啦~"

# 复制时自动追加版权相关说明
copyright_notice:
  enabled: true
  threshold: 150
  template: |
    $NEWLINE
    -------------------------
    该内容采用 CC BY-NC-SA 4.0 许可协议，著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
    作者：$AUTHOR
    来源：$TITLE
    链接：$LINK

# Friends 友链相关内容
friends:
  href: "friends"
  page:
    title: "好伙伴们"
    comments: false
    description: "好伙伴们在哪里~"
    updated: "2021-01-18"
  list: []
  # - name: "链接的名称"
  #   bio: "链接的描述文本"
  #   avatar: "链接使用的图标"
  #   link: "链接的地址"
  verify: true # 验证每个友链的可访问性，炸了会有提示

comments:
  template: ""
  enabled_at: []
  # - index
  # - post
  # - page

################## 额外的注入代码 ##################
additional_injections:
  head: "" # 搜索引擎的站点验证
  footer: "" # 托管信息等
  after_footer: "" # 站点分析脚本
