site_logo: https://ga.candinya.com/avatar/a7f9e15fef26e0a540edc977e21cb3eb
avatarUri: https://ga.candinya.com/avatar/a7f9e15fef26e0a540edc977e21cb3eb

topMenu:
  - label: 首页
    icon: home
    url: /
  - label: 档案馆
    icon: file
    url: /archives/
  - label: 好伙伴
    icon: paw
    url: /friends/
  - label: 链接
    icon: link
    submenu:
      - label: 作者博客
        url: https://candinya.com
      - label: 项目链接
        url: https://github.com/Candinya/Kratos-Rebirth

friends:
  list:
  - name: "猫猫①号"
    bio: "喵~"
    avatar: "../images/avatar.webp"
    link: "https://candinya.com"
  - name: "猫猫②号"
    bio: "喵喵~"
    avatar: "../images/avatar.webp"
    link: "https://candinya.com"
  - name: "猫猫⑨号"
    bio: "咪啪~"
    avatar: "../images/avatar.webp"
    link: "https://candinya.com"

posts:
  comments: 
    provider: gitalk

gitalk:
  clientID: 'GitHub Application Client ID'
  clientSecret: 'GitHub Application Client Secret'
  # repo: 'Kratos-Rebirth-Demo'
  # owner: 'Candinya'
  # admin: 
  #   - 'Candinya'
  # distractionFreeMode: false
